name: 🐞 Bug Report
description: Ermöglicht das Melden von Bugs
title: '[Bug] '
labels: ['bug']
body:
  - type: input
    id: summary
    attributes:
      label: Fehler-Überschrift
    required: true
  - type: textarea
    id: steps
    attributes:
      label: Schritte zur Reproduktion
    required: true
  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
    required: true
  - type: textarea
    id: actual
    attributes:
      label: Tatsächliches Verhalten
    required: true
