name: Deploy Frontend

on:
  workflow_run:
    workflows: ['React CI']
    types: ['completed']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: laravel-vite-build
          path: public/build

      # Hier deine eigentlichen Deploy-Schritte:
      # - rsync public/build auf deinen Server
      # - Copy nach /var/www/html
      # - o.ä.
