name: Deploy Frontend

on:
  workflow_run:
    workflows: ["React CI"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-react-build
          path: public/build

      # Hier deine Deploy-Schritte, z.B.:
      # - Kopieren nach /var/www/html
      # - rsync/scp
      # - GitHub Pages / Netlify / Surge usw.
