name: React CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['22.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        # kein working-directory nötig, weil dein package.json im Repo-Root liegt

      - name: Build assets
        run: npm run build
        # dieser Befehl nutzt Vite und schreibt standardmäßig nach public/build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: laravel-vite-build
          path: public/build
