name: Deploy Frontend

on:
  workflow_run:
    workflows: ["Build Frontend"]
    types:
      - completed

jobs:
  download-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download frontend-dist artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

      # Hier Deployment-Schritte ergänzen, z.B.:
      # - Copy files to webroot
      # - rsync / scp
      # - GitHub Pages / Netlify / Surge
