# .github/workflows/react-ci.yml
name: React CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # 1) Checkout deines Repos
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Node.js einrichten
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3) Abhängigkeiten installieren (im frontend-Ordner)
      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      # 4) Tests ausführen
      - name: Run tests
        run: npm test -- --watchAll=false
        working-directory: frontend

      # 5) Produktions-Build
      - name: Build
        run: npm run build
        working-directory: frontend

      # 6) Artifakte speichern (upload-artifact v2)
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-dist
          path: frontend/dist
